### ISSUE TITLE
작성한 ERD에 맞게, Entity를 설계한다.

### ISSUE THREAD

**Issue by kawkmin** [kawkmin/eBrainSoft_Assignments#1]
## 📝 Description

작성한 ERD에 맞게, Entity를 설계합니다.

## ☑️ TODO

- [ ] 게시판 Entity를 생성합니다.
- [ ] 카테고리 Entity를 생성합니다.
- [ ] 댓글 Entity를 생성합니다.
- [ ] 첨부파일 Entity를 생성합니다.
