### ISSUE TITLE
작성한 ERD에 맞게 Entity,DAO를 작성한다.

### ISSUE THREAD

**Issue by kawkmin** [kawkmin/eBrainSoft_Assignments#17]
## 📝 Description

작성된 ERD에 맞게 Entity 및 DAO를 생성합니다.

## ☑️ TODO

- [x] 게시판 Entity, DAO를 생성합니다.
- [x] 카테고리 Entity, DAO를 생성합니다.
- [x] 댓글 Entity, DAO를 생성합니다.
- [x] 첨부파일 Entity, DAO를 생성합니다.
