### ISSUE TITLE
작성한 ERD에 맞게 DAO 및 mapper xml을 작성한다.

### ISSUE THREAD

**Issue by kawkmin** [kawkmin/eBrainSoft_Assignments#25]
## 📝 Description

작성한 ERD에 맞게 DAO 작성합니다.

## ☑️ TODO

- [x] 게시판 DAO 및 mapper xml을 생성합니다.
- [x] 카테고리 DAO 및 mapper xml을 생성합니다.
- [x] 댓글 DAO 및 mapper xml을 생성합니다.
- [x] 첨부파일 DAO 및 mapper xml을 생성합니다.
