### ISSUE TITLE
설계된 ERD에 맞게 Entity 및 DAO 작성

### ISSUE THREAD

**Issue by kawkmin** [kawkmin/eBrainSoft_Assignments#44]
## 📝 Description

ERD에 맞게 Entity 및 DAO를 작성합니다.

## ☑️ TODO

- [x] 작성 시간 및 업데이트 시간을 가진 BaseEntity를 작성합니다.
- [x] 게시판 관련 Entity 및 DAO를 작성합니다.
- [x] 댓글 관련 Entity 및 DAO를 작성합니다.
- [x] 카테고리 관련 Entity 및 DAO를 작성합니다.
- [x] 파일 관련 Entity 및 DAO를 작성합니다.
